// <auto-generated />
using System;
using AspNetCoreMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HackAtHome.Migrations
{
    [DbContext(typeof(HackAtHomeContext))]
    [Migration("20210327103304_IzmjenaZahtjeva")]
    partial class IzmjenaZahtjeva
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HackAtHome.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Dijete")
                        .HasColumnType("bit");

                    b.Property<string>("GeografskaDuzina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeografskaSirina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OsobaSaPoteskocamaSluha")
                        .HasColumnType("bit");

                    b.Property<bool>("OsobaUIzolaciji")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StarijaOsoba")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("HackAtHome.Models.Volonter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Dostava")
                        .HasColumnType("bit");

                    b.Property<string>("GeografskaDuzina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeografskaSirina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MedicinskiRadnik")
                        .HasColumnType("bit");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Tutor")
                        .HasColumnType("bit");

                    b.Property<bool>("Vakcinisan")
                        .HasColumnType("bit");

                    b.Property<bool>("ZnakovniJezik")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Volonter");
                });

            modelBuilder.Entity("HackAtHome.Models.Zahtjev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Dostava")
                        .HasColumnType("bit");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<bool>("MedicinskaPomoc")
                        .HasColumnType("bit");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Tutor")
                        .HasColumnType("bit");

                    b.Property<bool>("Vakcinisan")
                        .HasColumnType("bit");

                    b.Property<bool>("Zavrseno")
                        .HasColumnType("bit");

                    b.Property<bool>("ZnakovniJezik")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Zahtjev");
                });
#pragma warning restore 612, 618
        }
    }
}
